<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>dev.leavesantiillegal</groupId>
        <artifactId>LeavesAntiIllegal</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>LeavesAntiIllegal-plugin</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>${spigot.api.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.Querz</groupId>
            <artifactId>NBT</artifactId>
            <version>6.1</version>
        </dependency>
        <dependency>
            <groupId>dev.leavesantiillegal</groupId>
            <artifactId>LeavesAntiIllegal-v1_20_1</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>dev.leavesantiillegal</groupId>
            <artifactId>LeavesAntiIllegal-v1_21</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>dev.leavesantiillegal</groupId>
            <artifactId>LeavesAntiIllegal-v26_2</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>LeavesAntiIllegal-${project.version}</finalName>
        <sourceDirectory>${project.basedir}/../src/main/java</sourceDirectory>
        <resources>
            <resource>
                <directory>${project.basedir}/../src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <relocations>
                                <relocation>
                                    <pattern>net.querz</pattern>
                                    <shadedPattern>dev.leavesantiillegal.lib.querz</shadedPattern>
                                </relocation>
                            </relocations>
                            <artifactSet>
                                <includes>
                                    <include>com.github.Querz:NBT</include>
                                    <include>dev.leavesantiillegal:LeavesAntiIllegal-v1_20_1</include>
                                    <include>dev.leavesantiillegal:LeavesAntiIllegal-v1_21</include>
                                    <include>dev.leavesantiillegal:LeavesAntiIllegal-v26_2</include>
                                </includes>
                            </artifactSet>
                            <filters>
                                <filter>
                                    <artifact>com.github.Querz:NBT</artifact>
                                    <excludes>
                                        <exclude>META-INF/MANIFEST.MF</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
